use rust_jsonpath::{errors::JSONPathError, query::Query};

macro_rules! assert_valid {
    ($($name:ident: $value:expr,)*) => {
    mod cts_valid {
        use super::*;
        $(
            #[allow(non_snake_case)]
            #[test]
            fn $name() -> Result<(), JSONPathError> {
                let input = $value;
                Query::new(input)?;
                Ok(())
            }
        )*
        }
    }
}

macro_rules! assert_invalid {
    ($($name:ident: $value:expr,)*) => {
    mod cts_invalid {
        use super::*;
        $(
            #[allow(non_snake_case)]
            #[test]
            #[should_panic]
            fn $name() {
                let input = $value;
                Query::new(input).unwrap();
            }
        )*
        }
    }
}

assert_valid! {
    basic__root0: "$",
    basic__name_shorthand0: "$.a",
    basic__name_shorthand__extended_unicode__0: "$.☺",
    basic__name_shorthand__underscore0: "$._",
    basic__name_shorthand__absent_data0: "$.c",
    basic__name_shorthand__array_data0: "$.a",
    basic__wildcard_shorthand__object_data0: "$.*",
    basic__wildcard_shorthand__array_data0: "$.*",
    basic__wildcard_selector__array_data0: "$[*]",
    basic__wildcard_shorthand__then_name_shorthand0: "$.*.a",
    basic__multiple_selectors0: "$[0,2]",
    basic__multiple_selectors__name_and_index__array_data0: "$['a',1]",
    basic__multiple_selectors__name_and_index__object_data0: "$['a',1]",
    basic__multiple_selectors__index_and_slice0: "$[1,5:7]",
    basic__multiple_selectors__index_and_slice__overlapping0: "$[1,0:3]",
    basic__multiple_selectors__duplicate_index0: "$[1,1]",
    basic__multiple_selectors__wildcard_and_index0: "$[*,1]",
    basic__multiple_selectors__wildcard_and_name0: "$[*,'a']",
    basic__multiple_selectors__wildcard_and_slice0: "$[*,0:2]",
    basic__multiple_selectors__multiple_wildcards0: "$[*,*]",
    basic__descendant_segment__index0: "$..[1]",
    basic__descendant_segment__name_shorthand0: "$..a",
    basic__descendant_segment__wildcard_shorthand__array_data0: "$..*",
    basic__descendant_segment__wildcard_selector__array_data0: "$..[*]",
    basic__descendant_segment__wildcard_selector__nested_arrays0: "$..[*]",
    basic__descendant_segment__wildcard_selector__nested_objects0: "$..[*]",
    basic__descendant_segment__wildcard_shorthand__object_data0: "$..*",
    basic__descendant_segment__wildcard_shorthand__nested_data0: "$..*",
    basic__descendant_segment__multiple_selectors0: "$..['a','d']",
    basic__descendant_segment__object_traversal__multiple_selectors0: "$..['a','d']",
    filter__existence0: "$[?@.a]",
    filter__existence__present_with_null0: "$[?@.a]",
    filter__equals_string__single_quotes0: "$[?@.a=='b']",
    filter__equals_numeric_string__single_quotes0: "$[?@.a=='1']",
    filter__equals_string__double_quotes0: "$[?@.a==\"b\"]",
    filter__equals_numeric_string__double_quotes0: "$[?@.a==\"1\"]",
    filter__equals_number0: "$[?@.a==1]",
    filter__equals_null0: "$[?@.a==null]",
    filter__equals_null__absent_from_data0: "$[?@.a==null]",
    filter__equals_true0: "$[?@.a==true]",
    filter__equals_false0: "$[?@.a==false]",
    filter__deep_equality__arrays0: "$[?@.a==@.b]",
    filter__deep_equality__objects0: "$[?@.a==@.b]",
    filter__not_equals_string__single_quotes0: "$[?@.a!='b']",
    filter__not_equals_numeric_string__single_quotes0: "$[?@.a!='1']",
    filter__not_equals_string__single_quotes__different_type0: "$[?@.a!='b']",
    filter__not_equals_string__double_quotes0: "$[?@.a!=\"b\"]",
    filter__not_equals_numeric_string__double_quotes0: "$[?@.a!=\"1\"]",
    filter__not_equals_string__double_quotes__different_types0: "$[?@.a!=\"b\"]",
    filter__not_equals_number0: "$[?@.a!=1]",
    filter__not_equals_number__different_types0: "$[?@.a!=1]",
    filter__not_equals_null0: "$[?@.a!=null]",
    filter__not_equals_null__absent_from_data0: "$[?@.a!=null]",
    filter__not_equals_true0: "$[?@.a!=true]",
    filter__not_equals_false0: "$[?@.a!=false]",
    filter__less_than_string__single_quotes0: "$[?@.a<'c']",
    filter__less_than_string__double_quotes0: "$[?@.a<\"c\"]",
    filter__less_than_number0: "$[?@.a<10]",
    filter__less_than_null0: "$[?@.a<null]",
    filter__less_than_true0: "$[?@.a<true]",
    filter__less_than_false0: "$[?@.a<false]",
    filter__less_than_or_equal_to_string__single_quotes0: "$[?@.a<='c']",
    filter__less_than_or_equal_to_string__double_quotes0: "$[?@.a<=\"c\"]",
    filter__less_than_or_equal_to_number0: "$[?@.a<=10]",
    filter__less_than_or_equal_to_null0: "$[?@.a<=null]",
    filter__less_than_or_equal_to_true0: "$[?@.a<=true]",
    filter__less_than_or_equal_to_false0: "$[?@.a<=false]",
    filter__greater_than_string__single_quotes0: "$[?@.a>'c']",
    filter__greater_than_string__double_quotes0: "$[?@.a>\"c\"]",
    filter__greater_than_number0: "$[?@.a>10]",
    filter__greater_than_null0: "$[?@.a>null]",
    filter__greater_than_true0: "$[?@.a>true]",
    filter__greater_than_false0: "$[?@.a>false]",
    filter__greater_than_or_equal_to_string__single_quotes0: "$[?@.a>='c']",
    filter__greater_than_or_equal_to_string__double_quotes0: "$[?@.a>=\"c\"]",
    filter__greater_than_or_equal_to_number0: "$[?@.a>=10]",
    filter__greater_than_or_equal_to_null0: "$[?@.a>=null]",
    filter__greater_than_or_equal_to_true0: "$[?@.a>=true]",
    filter__greater_than_or_equal_to_false0: "$[?@.a>=false]",
    filter__exists_and_not_equals_null__absent_from_data0: "$[?@.a&&@.a!=null]",
    filter__exists_and_exists__data_false0: "$[?@.a&&@.b]",
    filter__exists_or_exists__data_false0: "$[?@.a||@.b]",
    filter__and0: "$[?@.a>0&&@.a<10]",
    filter__or0: "$[?@.a=='b'||@.a=='d']",
    filter__not_expression0: "$[?!(@.a=='b')]",
    filter__not_exists0: "$[?!@.a]",
    filter__not_exists__data_null0: "$[?!@.a]",
    filter__nested0: "$[?@[?@>1]]",
    filter__multiple_selectors0: "$[?@.a,?@.b]",
    filter__multiple_selectors__comparison0: "$[?@.a=='b',?@.b=='x']",
    filter__multiple_selectors__overlapping0: "$[?@.a,?@.d]",
    filter__multiple_selectors__filter_and_index0: "$[?@.a,1]",
    filter__multiple_selectors__filter_and_wildcard0: "$[?@.a,*]",
    filter__multiple_selectors__filter_and_slice0: "$[?@.a,1:]",
    filter__multiple_selectors__comparison_filter__index_and_slice0: "$[1, ?@.a=='b', 1:]",
    filter__equals_number__zero_and_negative_zero0: "$[?@.a==-0]",
    filter__equals_number__with_and_without_decimal_fraction0: "$[?@.a==1.0]",
    filter__equals_number__exponent0: "$[?@.a==1e2]",
    filter__equals_number__positive_exponent0: "$[?@.a==1e+2]",
    filter__equals_number__negative_exponent0: "$[?@.a==1e-2]",
    filter__equals_number__decimal_fraction0: "$[?@.a==1.1]",
    filter__equals_number__decimal_fraction__exponent0: "$[?@.a==1.1e2]",
    filter__equals_number__decimal_fraction__positive_exponent0: "$[?@.a==1.1e+2]",
    filter__equals_number__decimal_fraction__negative_exponent0: "$[?@.a==1.1e-2]",
    filter__equals__special_nothing0: "$.values[?length(@.a) == value($..c)]",
    filter__object_data0: "$[?@<3]",
    filter__and_binds_more_tightly_than_or0: "$[?@.a || @.b && @.b]",
    filter__left_to_right_evaluation0: "$[?@.b && @.b || @.a]",
    filter__group_terms__left0: "$[?(@.a || @.b) && @.a]",
    filter__group_terms__right0: "$[?@.a && (@.b || @.a)]",
    filter__group_terms__or_before_and0: "$[?(@.a || @.b) && @.b]",
    index_selector__first_element0: "$[0]",
    index_selector__second_element0: "$[1]",
    index_selector__out_of_bound0: "$[2]",
    index_selector__negative0: "$[-1]",
    index_selector__more_negative0: "$[-2]",
    index_selector__negative_out_of_bound0: "$[-3]",
    index_selector__on_object0: "$[0]",
    name_selector__double_quotes0: "$[\"a\"]",
    name_selector__double_quotes__absent_data0: "$[\"c\"]",
    name_selector__double_quotes__array_data0: "$[\"a\"]",
    name_selector__double_quotes__embedded_U_00200: "$[\" \"]",
    name_selector__double_quotes__escaped_double_quote0: "$[\"\\\"\"]",
    name_selector__double_quotes__escaped_reverse_solidus0: "$[\"\\\\\"]",
    name_selector__double_quotes__escaped_solidus0: "$[\"\\/\"]",
    name_selector__double_quotes__escaped_backspace0: "$[\"\\b\"]",
    name_selector__double_quotes__escaped_form_feed0: "$[\"\\f\"]",
    name_selector__double_quotes__escaped_line_feed0: "$[\"\\n\"]",
    name_selector__double_quotes__escaped_carriage_return0: "$[\"\\r\"]",
    name_selector__double_quotes__escaped_tab0: "$[\"\\t\"]",
    name_selector__double_quotes__escaped____upper_case_hex0: "$[\"\\u263A\"]",
    name_selector__double_quotes__escaped____lower_case_hex0: "$[\"\\u263a\"]",
    name_selector__double_quotes__surrogate_pair__0: "$[\"\\uD834\\uDD1E\"]",
    name_selector__double_quotes__surrogate_pair__1: "$[\"\\uD83D\\uDE00\"]",
    name_selector__single_quotes0: "$['a']",
    name_selector__single_quotes__absent_data0: "$['c']",
    name_selector__single_quotes__array_data0: "$['a']",
    name_selector__single_quotes__embedded_U_00200: "$[' ']",
    name_selector__single_quotes__escaped_single_quote0: "$['\\'']",
    name_selector__single_quotes__escaped_reverse_solidus0: "$['\\\\']",
    name_selector__single_quotes__escaped_solidus0: "$['\\/']",
    name_selector__single_quotes__escaped_backspace0: "$['\\b']",
    name_selector__single_quotes__escaped_form_feed0: "$['\\f']",
    name_selector__single_quotes__escaped_line_feed0: "$['\\n']",
    name_selector__single_quotes__escaped_carriage_return0: "$['\\r']",
    name_selector__single_quotes__escaped_tab0: "$['\\t']",
    name_selector__single_quotes__escaped____upper_case_hex0: "$['\\u263A']",
    name_selector__single_quotes__escaped____lower_case_hex0: "$['\\u263a']",
    name_selector__single_quotes__surrogate_pair__0: "$['\\uD834\\uDD1E']",
    name_selector__single_quotes__surrogate_pair__1: "$['\\uD83D\\uDE00']",
    name_selector__double_quotes__empty0: "$[\"\"]",
    name_selector__single_quotes__empty0: "$['']",
    slice_selector__slice_selector0: "$[1:3]",
    slice_selector__slice_selector_with_step0: "$[1:6:2]",
    slice_selector__slice_selector_with_everything_omitted__short_form0: "$[:]",
    slice_selector__slice_selector_with_everything_omitted__long_form0: "$[::]",
    slice_selector__slice_selector_with_start_omitted0: "$[:2]",
    slice_selector__slice_selector_with_start_and_end_omitted0: "$[::2]",
    slice_selector__negative_step_with_default_start_and_end0: "$[::-1]",
    slice_selector__negative_step_with_default_start0: "$[:0:-1]",
    slice_selector__negative_step_with_default_end0: "$[2::-1]",
    slice_selector__larger_negative_step0: "$[::-2]",
    slice_selector__negative_range_with_default_step0: "$[-1:-3]",
    slice_selector__negative_range_with_negative_step0: "$[-1:-3:-1]",
    slice_selector__negative_range_with_larger_negative_step0: "$[-1:-6:-2]",
    slice_selector__larger_negative_range_with_larger_negative_step0: "$[-1:-7:-2]",
    slice_selector__negative_from__positive_to0: "$[-5:7]",
    slice_selector__negative_from0: "$[-2:]",
    slice_selector__positive_from__negative_to0: "$[1:-1]",
    slice_selector__negative_from__positive_to__negative_step0: "$[-1:1:-1]",
    slice_selector__positive_from__negative_to__negative_step0: "$[7:-5:-1]",
    slice_selector__zero_step0: "$[1:2:0]",
    slice_selector__empty_range0: "$[2:2]",
    slice_selector__slice_selector_with_everything_omitted_with_empty_array0: "$[:]",
    slice_selector__negative_step_with_empty_array0: "$[::-1]",
    slice_selector__maximal_range_with_positive_step0: "$[0:10]",
    slice_selector__maximal_range_with_negative_step0: "$[9:0:-1]",
    slice_selector__excessively_large_to_value0: "$[2:113667776004]",
    slice_selector__excessively_small_from_value0: "$[-113667776004:1]",
    slice_selector__excessively_large_from_value_with_negative_step0: "$[113667776004:0:-1]",
    slice_selector__excessively_small_to_value_with_negative_step0: "$[3:-113667776004:-1]",
    slice_selector__excessively_large_step0: "$[1:10:113667776004]",
    slice_selector__excessively_small_step0: "$[-1:-10:-113667776004]",
    functions__count__count_function0: "$[?count(@..*)>2]",
    functions__count__single_node_arg0: "$[?count(@.a)>1]",
    functions__count__multiple_selector_arg0: "$[?count(@['a','d'])>1]",
    functions__length__string_data0: "$[?length(@.a)>=2]",
    functions__length__string_data__unicode0: "$[?length(@)==2]",
    functions__length__array_data0: "$[?length(@.a)>=2]",
    functions__length__missing_data0: "$[?length(@.a)>=2]",
    functions__length__number_arg0: "$[?length(1)>=2]",
    functions__length__true_arg0: "$[?length(true)>=2]",
    functions__length__false_arg0: "$[?length(false)>=2]",
    functions__length__null_arg0: "$[?length(null)>=2]",
    functions__length__arg_is_a_function_expression0: "$.values[?length(@.a)==length(value($..c))]",
    functions__length__arg_is_special_nothing0: "$[?length(value(@.a))>0]",
    functions__match__found_match0: "$[?match(@.a, 'a.*')]",
    functions__match__double_quotes0: "$[?match(@.a, \"a.*\")]",
    functions__match__regex_from_the_document0: "$.values[?match(@, $.regex)]",
    functions__match__don_t_select_match0: "$[?!match(@.a, 'a.*')]",
    functions__match__not_a_match0: "$[?match(@.a, 'a.*')]",
    functions__match__select_non_match0: "$[?!match(@.a, 'a.*')]",
    functions__match__non_string_first_arg0: "$[?match(1, 'a.*')]",
    functions__match__non_string_second_arg0: "$[?match(@.a, 1)]",
    functions__match__filter__match_function__unicode_char_class__uppercase0: "$[?match(@, '\\\\p{Lu}')]",
    functions__match__filter__match_function__unicode_char_class_negated__uppercase0: "$[?match(@, '\\\\P{Lu}')]",
    functions__match__filter__match_function__unicode__surrogate_pair0: "$[?match(@, 'a.b')]",
    functions__match__arg_is_a_function_expression0: "$.values[?match(@.a, value($..['regex']))]",
    functions__search__at_the_end0: "$[?search(@.a, 'a.*')]",
    functions__search__double_quotes0: "$[?search(@.a, \"a.*\")]",
    functions__search__at_the_start0: "$[?search(@.a, 'a.*')]",
    functions__search__in_the_middle0: "$[?search(@.a, 'a.*')]",
    functions__search__regex_from_the_document0: "$.values[?search(@, $.regex)]",
    functions__search__don_t_select_match0: "$[?!search(@.a, 'a.*')]",
    functions__search__not_a_match0: "$[?search(@.a, 'a.*')]",
    functions__search__select_non_match0: "$[?!search(@.a, 'a.*')]",
    functions__search__non_string_first_arg0: "$[?search(1, 'a.*')]",
    functions__search__non_string_second_arg0: "$[?search(@.a, 1)]",
    functions__search__filter__search_function__unicode_char_class__uppercase0: "$[?search(@, '\\\\p{Lu}')]",
    functions__search__filter__search_function__unicode_char_class_negated__uppercase0: "$[?search(@, '\\\\P{Lu}')]",
    functions__search__filter__search_function__unicode__surrogate_pair0: "$[?search(@, 'a.b')]",
    functions__search__arg_is_a_function_expression0: "$.values[?search(@, value($..['regex']))]",
    functions__value__single_value_nodelist0: "$[?value(@.*)==4]",
    functions__value__multi_value_nodelist0: "$[?value(@.*)==4]",
    whitespace__filter__space_between_question_mark_and_expression0: "$[? @.a]",
    whitespace__filter__newline_between_question_mark_and_expression0: "$[?\n@.a]",
    whitespace__filter__tab_between_question_mark_and_expression0: "$[?\t@.a]",
    whitespace__filter__return_between_question_mark_and_expression0: "$[?\r@.a]",
    whitespace__filter__space_between_question_mark_and_parenthesized_expression0: "$[? (@.a)]",
    whitespace__filter__newline_between_question_mark_and_parenthesized_expression0: "$[?\n(@.a)]",
    whitespace__filter__tab_between_question_mark_and_parenthesized_expression0: "$[?\t(@.a)]",
    whitespace__filter__return_between_question_mark_and_parenthesized_expression0: "$[?\r(@.a)]",
    whitespace__filter__space_between_parenthesized_expression_and_bracket0: "$[?(@.a) ]",
    whitespace__filter__newline_between_parenthesized_expression_and_bracket0: "$[?(@.a)\n]",
    whitespace__filter__tab_between_parenthesized_expression_and_bracket0: "$[?(@.a)\t]",
    whitespace__filter__return_between_parenthesized_expression_and_bracket0: "$[?(@.a)\r]",
    whitespace__filter__space_between_bracket_and_question_mark0: "$[ ?@.a]",
    whitespace__filter__newline_between_bracket_and_question_mark0: "$[\n?@.a]",
    whitespace__filter__tab_between_bracket_and_question_mark0: "$[\t?@.a]",
    whitespace__filter__return_between_bracket_and_question_mark0: "$[\r?@.a]",
    whitespace__functions__space_between_parenthesis_and_arg0: "$[?count( @.*)==1]",
    whitespace__functions__newline_between_parenthesis_and_arg0: "$[?count(\n@.*)==1]",
    whitespace__functions__tab_between_parenthesis_and_arg0: "$[?count(\t@.*)==1]",
    whitespace__functions__return_between_parenthesis_and_arg0: "$[?count(\r@.*)==1]",
    whitespace__functions__space_between_arg_and_comma0: "$[?search(@ ,'[a-z]+')]",
    whitespace__functions__newline_between_arg_and_comma0: "$[?search(@\n,'[a-z]+')]",
    whitespace__functions__tab_between_arg_and_comma0: "$[?search(@\t,'[a-z]+')]",
    whitespace__functions__return_between_arg_and_comma0: "$[?search(@\r,'[a-z]+')]",
    whitespace__functions__space_between_comma_and_arg0: "$[?search(@, '[a-z]+')]",
    whitespace__functions__newline_between_comma_and_arg0: "$[?search(@,\n'[a-z]+')]",
    whitespace__functions__tab_between_comma_and_arg0: "$[?search(@,\t'[a-z]+')]",
    whitespace__functions__return_between_comma_and_arg0: "$[?search(@,\r'[a-z]+')]",
    whitespace__functions__space_between_arg_and_parenthesis0: "$[?count(@.* )==1]",
    whitespace__functions__newline_between_arg_and_parenthesis0: "$[?count(@.*\n)==1]",
    whitespace__functions__tab_between_arg_and_parenthesis0: "$[?count(@.*\t)==1]",
    whitespace__functions__return_between_arg_and_parenthesis0: "$[?count(@.*\r)==1]",
    whitespace__functions__spaces_in_a_relative_singular_selector0: "$[?length(@ .a .b) == 3]",
    whitespace__functions__newlines_in_a_relative_singular_selector0: "$[?length(@\n.a\n.b) == 3]",
    whitespace__functions__tabs_in_a_relative_singular_selector0: "$[?length(@\t.a\t.b) == 3]",
    whitespace__functions__returns_in_a_relative_singular_selector0: "$[?length(@\r.a\r.b) == 3]",
    whitespace__functions__spaces_in_an_absolute_singular_selector0: "$..[?length(@)==length($ [0] .a)]",
    whitespace__functions__newlines_in_an_absolute_singular_selector0: "$..[?length(@)==length($\n[0]\n.a)]",
    whitespace__functions__tabs_in_an_absolute_singular_selector0: "$..[?length(@)==length($\t[0]\t.a)]",
    whitespace__functions__returns_in_an_absolute_singular_selector0: "$..[?length(@)==length($\r[0]\r.a)]",
    whitespace__operators__space_before___0: "$[?@.a ||@.b]",
    whitespace__operators__newline_before___0: "$[?@.a\n||@.b]",
    whitespace__operators__tab_before___0: "$[?@.a\t||@.b]",
    whitespace__operators__return_before___0: "$[?@.a\r||@.b]",
    whitespace__operators__space_after___0: "$[?@.a|| @.b]",
    whitespace__operators__newline_after___0: "$[?@.a||\n@.b]",
    whitespace__operators__tab_after___0: "$[?@.a||\t@.b]",
    whitespace__operators__return_after___0: "$[?@.a||\r@.b]",
    whitespace__operators__space_before___1: "$[?@.a &&@.b]",
    whitespace__operators__newline_before___1: "$[?@.a\n&&@.b]",
    whitespace__operators__tab_before___1: "$[?@.a\t&&@.b]",
    whitespace__operators__return_before___1: "$[?@.a\r&&@.b]",
    whitespace__operators__space_after___1: "$[?@.a&& @.b]",
    whitespace__operators__newline_after___1: "$[?@.a&& @.b]",
    whitespace__operators__tab_after___1: "$[?@.a&& @.b]",
    whitespace__operators__return_after___1: "$[?@.a&& @.b]",
    whitespace__operators__space_before___2: "$[?@.a ==@.b]",
    whitespace__operators__newline_before___2: "$[?@.a\n==@.b]",
    whitespace__operators__tab_before___2: "$[?@.a\t==@.b]",
    whitespace__operators__return_before___2: "$[?@.a\r==@.b]",
    whitespace__operators__space_after___2: "$[?@.a== @.b]",
    whitespace__operators__newline_after___2: "$[?@.a==\n@.b]",
    whitespace__operators__tab_after___2: "$[?@.a==\t@.b]",
    whitespace__operators__return_after___2: "$[?@.a==\r@.b]",
    whitespace__operators__space_before___3: "$[?@.a !=@.b]",
    whitespace__operators__newline_before___3: "$[?@.a\n!=@.b]",
    whitespace__operators__tab_before___3: "$[?@.a\t!=@.b]",
    whitespace__operators__return_before___3: "$[?@.a\r!=@.b]",
    whitespace__operators__space_after___3: "$[?@.a!= @.b]",
    whitespace__operators__newline_after___3: "$[?@.a!=\n@.b]",
    whitespace__operators__tab_after___3: "$[?@.a!=\t@.b]",
    whitespace__operators__return_after___3: "$[?@.a!=\r@.b]",
    whitespace__operators__space_before__0: "$[?@.a <@.b]",
    whitespace__operators__newline_before__0: "$[?@.a\n<@.b]",
    whitespace__operators__tab_before__0: "$[?@.a\t<@.b]",
    whitespace__operators__return_before__0: "$[?@.a\r<@.b]",
    whitespace__operators__space_after__0: "$[?@.a< @.b]",
    whitespace__operators__newline_after__0: "$[?@.a<\n@.b]",
    whitespace__operators__tab_after__0: "$[?@.a<\t@.b]",
    whitespace__operators__return_after__0: "$[?@.a<\r@.b]",
    whitespace__operators__space_before__1: "$[?@.b >@.a]",
    whitespace__operators__newline_before__1: "$[?@.b\n>@.a]",
    whitespace__operators__tab_before__1: "$[?@.b\t>@.a]",
    whitespace__operators__return_before__1: "$[?@.b\r>@.a]",
    whitespace__operators__space_after__1: "$[?@.b> @.a]",
    whitespace__operators__newline_after__1: "$[?@.b>\n@.a]",
    whitespace__operators__tab_after__1: "$[?@.b>\t@.a]",
    whitespace__operators__return_after__1: "$[?@.b>\r@.a]",
    whitespace__operators__space_before___4: "$[?@.a <=@.b]",
    whitespace__operators__newline_before___4: "$[?@.a\n<=@.b]",
    whitespace__operators__tab_before___4: "$[?@.a\t<=@.b]",
    whitespace__operators__return_before___4: "$[?@.a\r<=@.b]",
    whitespace__operators__space_after___4: "$[?@.a<= @.b]",
    whitespace__operators__newline_after___4: "$[?@.a<=\n@.b]",
    whitespace__operators__tab_after___4: "$[?@.a<=\t@.b]",
    whitespace__operators__return_after___4: "$[?@.a<=\r@.b]",
    whitespace__operators__space_before___5: "$[?@.b >=@.a]",
    whitespace__operators__newline_before___5: "$[?@.b\n>=@.a]",
    whitespace__operators__tab_before___5: "$[?@.b\t>=@.a]",
    whitespace__operators__return_before___5: "$[?@.b\r>=@.a]",
    whitespace__operators__space_after___5: "$[?@.b>= @.a]",
    whitespace__operators__newline_after___5: "$[?@.b>=\n@.a]",
    whitespace__operators__tab_after___5: "$[?@.b>=\t@.a]",
    whitespace__operators__return_after___5: "$[?@.b>=\r@.a]",
    whitespace__operators__space_between_logical_not_and_test_expression0: "$[?! @.a]",
    whitespace__operators__newline_between_logical_not_and_test_expression0: "$[?!\n@.a]",
    whitespace__operators__tab_between_logical_not_and_test_expression0: "$[?!\t@.a]",
    whitespace__operators__return_between_logical_not_and_test_expression0: "$[?!\r@.a]",
    whitespace__operators__space_between_logical_not_and_parenthesized_expression0: "$[?! (@.a=='b')]",
    whitespace__operators__newline_between_logical_not_and_parenthesized_expression0: "$[?!\n(@.a=='b')]",
    whitespace__operators__tab_between_logical_not_and_parenthesized_expression0: "$[?!\t(@.a=='b')]",
    whitespace__operators__return_between_logical_not_and_parenthesized_expression0: "$[?!\r(@.a=='b')]",
    whitespace__selectors__space_between_root_and_bracket0: "$ ['a']",
    whitespace__selectors__newline_between_root_and_bracket0: "$\n['a']",
    whitespace__selectors__tab_between_root_and_bracket0: "$\t['a']",
    whitespace__selectors__return_between_root_and_bracket0: "$\r['a']",
    whitespace__selectors__space_between_bracket_and_bracket0: "$['a'] ['b']",
    whitespace__selectors__newline_between_root_and_bracket1: "$['a'] \n['b']",
    whitespace__selectors__tab_between_root_and_bracket1: "$['a'] \t['b']",
    whitespace__selectors__return_between_root_and_bracket1: "$['a'] \r['b']",
    whitespace__selectors__space_between_root_and_dot0: "$ .a",
    whitespace__selectors__newline_between_root_and_dot0: "$\n.a",
    whitespace__selectors__tab_between_root_and_dot0: "$\t.a",
    whitespace__selectors__return_between_root_and_dot0: "$\r.a",
    whitespace__selectors__space_between_bracket_and_selector0: "$[ 'a']",
    whitespace__selectors__newline_between_bracket_and_selector0: "$[\n'a']",
    whitespace__selectors__tab_between_bracket_and_selector0: "$[\t'a']",
    whitespace__selectors__return_between_bracket_and_selector0: "$[\r'a']",
    whitespace__selectors__space_between_selector_and_bracket0: "$['a' ]",
    whitespace__selectors__newline_between_selector_and_bracket0: "$['a'\n]",
    whitespace__selectors__tab_between_selector_and_bracket0: "$['a'\t]",
    whitespace__selectors__return_between_selector_and_bracket0: "$['a'\r]",
    whitespace__selectors__space_between_selector_and_comma0: "$['a' ,'b']",
    whitespace__selectors__newline_between_selector_and_comma0: "$['a'\n,'b']",
    whitespace__selectors__tab_between_selector_and_comma0: "$['a'\t,'b']",
    whitespace__selectors__return_between_selector_and_comma0: "$['a'\r,'b']",
    whitespace__selectors__space_between_comma_and_selector0: "$['a', 'b']",
    whitespace__selectors__newline_between_comma_and_selector0: "$['a',\n'b']",
    whitespace__selectors__tab_between_comma_and_selector0: "$['a',\t'b']",
    whitespace__selectors__return_between_comma_and_selector0: "$['a',\r'b']",
    whitespace__slice__space_between_start_and_colon0: "$[1 :5:2]",
    whitespace__slice__newline_between_start_and_colon0: "$[1\n:5:2]",
    whitespace__slice__tab_between_start_and_colon0: "$[1\t:5:2]",
    whitespace__slice__return_between_start_and_colon0: "$[1\r:5:2]",
    whitespace__slice__space_between_colon_and_end0: "$[1: 5:2]",
    whitespace__slice__newline_between_colon_and_end0: "$[1:\n5:2]",
    whitespace__slice__tab_between_colon_and_end0: "$[1:\t5:2]",
    whitespace__slice__return_between_colon_and_end0: "$[1:\r5:2]",
    whitespace__slice__space_between_end_and_colon0: "$[1:5 :2]",
    whitespace__slice__newline_between_end_and_colon0: "$[1:5\n:2]",
    whitespace__slice__tab_between_end_and_colon0: "$[1:5\t:2]",
    whitespace__slice__return_between_end_and_colon0: "$[1:5\r:2]",
    whitespace__slice__space_between_colon_and_step0: "$[1:5: 2]",
    whitespace__slice__newline_between_colon_and_step0: "$[1:5:\n2]",
    whitespace__slice__tab_between_colon_and_step0: "$[1:5:\t2]",
    whitespace__slice__return_between_colon_and_step0: "$[1:5:\r2]",
}

assert_invalid! {
    basic__no_leading_whitespace0: " $",
    basic__no_trailing_whitespace0: "$ ",
    basic__name_shorthand__symbol0: "$.&",
    basic__name_shorthand__number0: "$.1",
    basic__multiple_selectors__space_instead_of_comma0: "$[0 2]",
    basic__empty_segment0: "$[]",
    basic__bald_descendant_segment0: "$..",
    filter__non_singular_query_in_comparison__slice0: "$[?@[0:0]==0]",
    filter__non_singular_query_in_comparison__all_children0: "$[?@[*]==0]",
    filter__non_singular_query_in_comparison__descendants0: "$[?@..a==0]",
    filter__non_singular_query_in_comparison__combined0: "$[?@.a[*].a==0]",
    filter__relative_non_singular_query__index__equal0: "$[?(@[0, 0]==42)]",
    filter__relative_non_singular_query__index__not_equal0: "$[?(@[0, 0]!=42)]",
    filter__relative_non_singular_query__index__less_or_equal0: "$[?(@[0, 0]<=42)]",
    filter__relative_non_singular_query__name__equal0: "$[?(@['a', 'a']==42)]",
    filter__relative_non_singular_query__name__not_equal0: "$[?(@['a', 'a']!=42)]",
    filter__relative_non_singular_query__name__less_or_equal0: "$[?(@['a', 'a']<=42)]",
    filter__relative_non_singular_query__combined__equal0: "$[?(@[0, '0']==42)]",
    filter__relative_non_singular_query__combined__not_equal0: "$[?(@[0, '0']!=42)]",
    filter__relative_non_singular_query__combined__less_or_equal0: "$[?(@[0, '0']<=42)]",
    filter__relative_non_singular_query__wildcard__equal0: "$[?(@.*==42)]",
    filter__relative_non_singular_query__wildcard__not_equal0: "$[?(@.*!=42)]",
    filter__relative_non_singular_query__wildcard__less_or_equal0: "$[?(@.*<=42)]",
    filter__relative_non_singular_query__slice__equal0: "$[?(@[0:0]==42)]",
    filter__relative_non_singular_query__slice__not_equal0: "$[?(@[0:0]!=42)]",
    filter__relative_non_singular_query__slice__less_or_equal0: "$[?(@[0:0]<=42)]",
    filter__absolute_non_singular_query__index__equal0: "$[?($[0, 0]==42)]",
    filter__absolute_non_singular_query__index__not_equal0: "$[?($[0, 0]!=42)]",
    filter__absolute_non_singular_query__index__less_or_equal0: "$[?($[0, 0]<=42)]",
    filter__absolute_non_singular_query__name__equal0: "$[?($['a', 'a']==42)]",
    filter__absolute_non_singular_query__name__not_equal0: "$[?($['a', 'a']!=42)]",
    filter__absolute_non_singular_query__name__less_or_equal0: "$[?($['a', 'a']<=42)]",
    filter__absolute_non_singular_query__combined__equal0: "$[?($[0, '0']==42)]",
    filter__absolute_non_singular_query__combined__not_equal0: "$[?($[0, '0']!=42)]",
    filter__absolute_non_singular_query__combined__less_or_equal0: "$[?($[0, '0']<=42)]",
    filter__absolute_non_singular_query__wildcard__equal0: "$[?($.*==42)]",
    filter__absolute_non_singular_query__wildcard__not_equal0: "$[?($.*!=42)]",
    filter__absolute_non_singular_query__wildcard__less_or_equal0: "$[?($.*<=42)]",
    filter__absolute_non_singular_query__slice__equal0: "$[?($[0:0]==42)]",
    filter__absolute_non_singular_query__slice__not_equal0: "$[?($[0:0]!=42)]",
    filter__absolute_non_singular_query__slice__less_or_equal0: "$[?($[0:0]<=42)]",
    filter__equals_number__decimal_fraction__no_fractional_digit0: "$[?@.a==1.]",
    index_selector__overflowing_index0: "$[231584178474632390847141970017375815706539969331281128078915168015826259279872]",
    index_selector__not_actually_an_index__overflowing_index_leads_into_general_text0: "$[231584178474632390847141970017375815706539969331281128078915168SomeRandomText]",
    index_selector__leading_00: "$[01]",
    index_selector__leading__00: "$[-01]",
    name_selector__double_quotes__invalid_escaped_single_quote0: "$[\"\\'\"]",
    name_selector__double_quotes__embedded_double_quote0: "$[\"\"\"]",
    name_selector__double_quotes__incomplete_escape0: "$[\"\\\"]",
    name_selector__single_quotes__invalid_escaped_double_quote0: "$['\\\"']",
    name_selector__single_quotes__embedded_single_quote0: "$[''']",
    name_selector__single_quotes__incomplete_escape0: "$['\\']",
    slice_selector__too_many_colons0: "$[1:2:3:4]",
    slice_selector__non_integer_array_index0: "$[1:2:a]",
    slice_selector__overflowing_to_value0: "$[2:231584178474632390847141970017375815706539969331281128078915168015826259279872]",
    slice_selector__underflowing_from_value0: "$[-231584178474632390847141970017375815706539969331281128078915168015826259279872:1]",
    slice_selector__overflowing_from_value_with_negative_step0: "$[231584178474632390847141970017375815706539969331281128078915168015826259279872:0:-1]",
    slice_selector__underflowing_to_value_with_negative_step0: "$[3:-231584178474632390847141970017375815706539969331281128078915168015826259279872:-1]",
    slice_selector__overflowing_step0: "$[1:10:231584178474632390847141970017375815706539969331281128078915168015826259279872]",
    slice_selector__underflowing_step0: "$[-1:-10:-231584178474632390847141970017375815706539969331281128078915168015826259279872]",
    functions__count__non_query_arg__number0: "$[?count(1)>2]",
    functions__count__non_query_arg__string0: "$[?count('string')>2]",
    functions__count__non_query_arg__true0: "$[?count(true)>2]",
    functions__count__non_query_arg__false0: "$[?count(false)>2]",
    functions__count__non_query_arg__null0: "$[?count(null)>2]",
    functions__count__result_must_be_compared0: "$[?count(@..*)]",
    functions__count__no_params0: "$[?count()==1]",
    functions__count__too_many_params0: "$[?count(@.a,@.b)==1]",
    functions__length__result_must_be_compared0: "$[?length(@.a)]",
    functions__length__no_params0: "$[?length()==1]",
    functions__length__too_many_params0: "$[?length(@.a,@.b)==1]",
    functions__length__non_singular_query_arg0: "$[?length(@.*)<3]",
    functions__match__result_cannot_be_compared0: "$[?match(@.a, 'a.*')==true]",
    functions__match__too_few_params0: "$[?match(@.a)==1]",
    functions__match__too_many_params0: "$[?match(@.a,@.b,@.c)==1]",
    functions__search__result_cannot_be_compared0: "$[?search(@.a, 'a.*')==true]",
    functions__search__too_few_params0: "$[?search(@.a)]",
    functions__search__too_many_params0: "$[?search(@.a,@.b,@.c)]",
    functions__value__too_few_params0: "$[?value()==4]",
    functions__value__too_many_params0: "$[?value(@.a,@.b)==4]",
    functions__value__result_must_be_compared0: "$[?value(@.a)]",
    whitespace__functions__space_between_function_name_and_parenthesis0: "$[?count (@.*)==1]",
    whitespace__functions__newline_between_function_name_and_parenthesis0: "$[?count\n(@.*)==1]",
    whitespace__functions__tab_between_function_name_and_parenthesis0: "$[?count\t(@.*)==1]",
    whitespace__functions__return_between_function_name_and_parenthesis0: "$[?count\r(@.*)==1]",
    whitespace__selectors__space_between_dot_and_name0: "$. a",
    whitespace__selectors__newline_between_dot_and_name0: "$.\na",
    whitespace__selectors__tab_between_dot_and_name0: "$.\ta",
    whitespace__selectors__return_between_dot_and_name0: "$.\ra",
    whitespace__selectors__space_between_recursive_descent_and_name0: "$.. a",
    whitespace__selectors__newline_between_recursive_descent_and_name0: "$..\na",
    whitespace__selectors__tab_between_recursive_descent_and_name0: "$..\ta",
    whitespace__selectors__return_between_recursive_descent_and_name0: "$..\ra",
}

#[test]
#[should_panic]
fn invalid_u13() {
    Query::new("$[\"\\u0013\"]").unwrap();
}

#[test]
#[should_panic(expected = "invalid escape sequence")]
fn invalid_escape() {
    Query::new("$['\\\"']").unwrap();
}

#[test]
#[should_panic(expected = "unclosed string")]
fn invalid_unescaped_single_quote() {
    Query::new("$[''']").unwrap();
}

#[test]
#[should_panic(expected = "argument 1 of count() must be of a 'Nodes' type")]
fn function_expects_nodes_type() {
    Query::new("$[?count(1)>2]").unwrap();
}
